### ISSUE TITLE
360 degree scene

### ISSUE THREAD

**Issue by NikitaVasilevN** [eckertzhang/Text2NeRF#5]
Hello, I tried to run your model to generate a 360 degree scene, but I faced with a problem. After 850 epochs, the following error appears
Epoch 851
lr0 =  0.02 
lr1 =  0.001
  1%|█▍                                                                                                                                                    | 1/103 [00:00<01:27,  1.16it/s]
Traceback (most recent call last):
  File "/workspace/t2n_docker_conda/Text2NeRF/text2nerf_main.py", line 672, in <module>
    reconstruction(args)
  File "/workspace/t2n_docker_conda/Text2NeRF/text2nerf_main.py", line 556, in reconstruction
    rgb_map, alphas_map, depth_map, weights, z_vals = renderer(rays_train, tensorf, chunk=args.batch_size,
  File "/workspace/t2n_docker_conda/Text2NeRF/renderer.py", line 42, in OctreeRender_trilinear_fast
    return torch.cat(rgbs), None, torch.cat(depth_maps), torch.cat(weights), torch.cat(z_val)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by yezifeiafei** [comment]
I got the same error.

**Comment by eckertzhang** [comment]
Sorry for the inconvenience. Please change the 'pose_traj=circle0' to 'pose_traj=circle'. Here,  'circle0' was used for early code testing and has been discarded.
